// Package api contains OpenAPI spec and code generated by go-swagger.
package api

//go:generate rm -rf model restapi
//go:generate swagger generate server --api-package op --model-package model --strict-responders --strict-additional-properties --keep-spec-order --exclude-main
//go:generate find restapi -maxdepth 1 -name "configure_*.go" -exec sed -i -e "/go:generate/d" {} ;
//go:generate salgen -destination=./client.go -package=vendor/github.com/go-gad/sal/examples/profile/storage vendor/github.com/go-gad/sal/examples/profile/storage Store