swagger: '2.0'

info:
  title: stock
  version: 0.2.0
  description: |
    # ...
    ## List of all custom errors
    First number is HTTP Status code, second is value of "code" field in returned JSON object, text description may or may not match "message" field in returned JSON object.
    - 409.1000: contact already exists
basePath: /
schemes:
  - http

definitions:
  # This model should match output of api.ServeError handler, to ensure
  # errors returned by go-swagger (like failed validation) use same
  # format as general errors returned by our handlers.
  # By default api.ServeError = github.com/go-openapi/errors.ServeError.
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code OR >= 600 with HTTP Status Code 422.
        type: integer
        format: int32
      message:
        type: string

  CurrencyValues:
    type: object
    required:
      - PRICE
    properties:
      CHANGE24HOUR:
        type: string
      CHANGEPCT24HOUR:
        type: string
      OPEN24HOUR:
        type: string
      VOLUME24HOUR:
        type: string
      VOLUME24HOURTO:
        type: string
      LOW24HOUR:
        type: string
      HIGH24HOUR:
        type: string
      PRICE:
        type: string
      SUPPLY:
        type: string
      MKTCAP:
        type: string

  CurrencyObject:
    type: object
    required:
      - key
    properties:
      key:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/CurrencyValues'

  CurrencyData:
    type: object
    required:
      - key
    properties:
      key:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/CurrencyObject'

  ResultCurrency:
    type: object
    required:
      - key
    properties:
      key:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/CurrencyData'

consumes:
  - application/json
produces:
  - application/json

responses:
  GenericError:
    description: General errors using same model as used by go-swagger for validation errors.
    schema:
      $ref: '#/definitions/Error'

paths:
  /price:
    get:
      operationId: Price
      description: get Currency Price
      parameters:
        - in: query
          name: fsyms
          type: string
        - in: query
          name: tsyms
          type: string
      responses:
        '200':
          description: response
          schema:
            type: object
            required:
              - result
            properties:
              result:
                type: object
        default: {$ref: '#/responses/GenericError'}