// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewTimeSeriesIntradayParams creates a new TimeSeriesIntradayParams object
// no default values defined in spec.
func NewTimeSeriesIntradayParams() TimeSeriesIntradayParams {

	return TimeSeriesIntradayParams{}
}

// TimeSeriesIntradayParams contains all the bound params for the time series intraday operation
// typically these are obtained from a http.Request
//
// swagger:parameters timeSeriesIntraday
type TimeSeriesIntradayParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	Function *string
	/*
	  In: query
	*/
	Interval *string
	/*
	  In: query
	*/
	Symbol *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTimeSeriesIntradayParams() beforehand.
func (o *TimeSeriesIntradayParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFunction, qhkFunction, _ := qs.GetOK("function")
	if err := o.bindFunction(qFunction, qhkFunction, route.Formats); err != nil {
		res = append(res, err)
	}

	qInterval, qhkInterval, _ := qs.GetOK("interval")
	if err := o.bindInterval(qInterval, qhkInterval, route.Formats); err != nil {
		res = append(res, err)
	}

	qSymbol, qhkSymbol, _ := qs.GetOK("symbol")
	if err := o.bindSymbol(qSymbol, qhkSymbol, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFunction binds and validates parameter Function from query.
func (o *TimeSeriesIntradayParams) bindFunction(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Function = &raw

	return nil
}

// bindInterval binds and validates parameter Interval from query.
func (o *TimeSeriesIntradayParams) bindInterval(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Interval = &raw

	return nil
}

// bindSymbol binds and validates parameter Symbol from query.
func (o *TimeSeriesIntradayParams) bindSymbol(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Symbol = &raw

	return nil
}
