// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// TimeSeriesIntradayOKCode is the HTTP code returned for type TimeSeriesIntradayOK
const TimeSeriesIntradayOKCode int = 200

/*TimeSeriesIntradayOK response

swagger:response timeSeriesIntradayOK
*/
type TimeSeriesIntradayOK struct {

	/*
	  In: Body
	*/
	Payload *TimeSeriesIntradayOKBody `json:"body,omitempty"`
}

// NewTimeSeriesIntradayOK creates TimeSeriesIntradayOK with default headers values
func NewTimeSeriesIntradayOK() *TimeSeriesIntradayOK {

	return &TimeSeriesIntradayOK{}
}

// WithPayload adds the payload to the time series intraday o k response
func (o *TimeSeriesIntradayOK) WithPayload(payload *TimeSeriesIntradayOKBody) *TimeSeriesIntradayOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the time series intraday o k response
func (o *TimeSeriesIntradayOK) SetPayload(payload *TimeSeriesIntradayOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TimeSeriesIntradayOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *TimeSeriesIntradayOK) TimeSeriesIntradayResponder() {}

/*TimeSeriesIntradayDefault time series intraday default

swagger:response timeSeriesIntradayDefault
*/
type TimeSeriesIntradayDefault struct {
	_statusCode int
}

// NewTimeSeriesIntradayDefault creates TimeSeriesIntradayDefault with default headers values
func NewTimeSeriesIntradayDefault(code int) *TimeSeriesIntradayDefault {
	if code <= 0 {
		code = 500
	}

	return &TimeSeriesIntradayDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the time series intraday default response
func (o *TimeSeriesIntradayDefault) WithStatusCode(code int) *TimeSeriesIntradayDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the time series intraday default response
func (o *TimeSeriesIntradayDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *TimeSeriesIntradayDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}

func (o *TimeSeriesIntradayDefault) TimeSeriesIntradayResponder() {}

type TimeSeriesIntradayNotImplementedResponder struct {
	middleware.Responder
}

func (*TimeSeriesIntradayNotImplementedResponder) TimeSeriesIntradayResponder() {}

func TimeSeriesIntradayNotImplemented() TimeSeriesIntradayResponder {
	return &TimeSeriesIntradayNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.TimeSeriesIntraday has not yet been implemented",
		),
	}
}

type TimeSeriesIntradayResponder interface {
	middleware.Responder
	TimeSeriesIntradayResponder()
}
